# Generated by Django 5.0.3 on 2024-03-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_productattribute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='изображения'),
        ),
    ]
