# Generated by Django 5.0.3 on 2024-03-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='news_images/', verbose_name='изображение'),
        ),
    ]
