# Generated by Django 5.0.3 on 2024-03-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
