# Generated by Django 5.0.2 on 2024-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product', to='news.tag', verbose_name='теги'),
        ),
    ]
