# Generated by Django 5.0.3 on 2024-05-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_product_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
